package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.json.JSONObject;

import java.util.Collection;
import java.util.Map;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {


    @Autowired //bean is auto-generated by spring
    private UserRepository userRepository;


    @PostMapping(path="/add", consumes="application/json") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestBody String request ) {
        final JSONObject obj = new JSONObject(request);
        String name = obj.getString("name");
        Integer age = obj.getInt("age");
        System.out.println(name);
        User n = new User();
        n.setName(name);
        n.setAge(age);
        userRepository.save(n);
        return "Saved";
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}



    // The above example explicitly specifies POST and GET for the two endpoints.
    // @RequestMapping maps all HTTP operations by default.